name: Test assume IAM role to AWS accounts with Resource Control Policy

on:
  - push

permissions:
  contents: read
  id-token: write

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::191072206499:role/tmp-github
      - run: aws sts get-caller-identity
